parameter checking for docker tag

diff --git a/bin/push-docker-image b/bin/push-docker-image
--- a/bin/push-docker-image
+++ b/bin/push-docker-image
@@ -2,9 +2,15 @@
 
 set -e +o pipefail
 
-if [ "$TRAVIS_BRANCH" == "master" ]; then
-    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
-    export DOCKER_IMAGE_TAG=$DOCKER_IMAGE:`bash ./bin/package-version`
-    docker tag $DOCKER_IMAGE $DOCKER_IMAGE_TAG
-    docker push $DOCKER_IMAGE_TAG
+if [[ "$1" =~ [0-9]+\.[0-9]+\.[0-9]+ ]]; then
+    if [ "$TRAVIS_BRANCH" == "master" ]; then
+        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
+        export DOCKER_IMAGE_TAG=$DOCKER_IMAGE:$1
+        docker tag $DOCKER_IMAGE $DOCKER_IMAGE_TAG
+        docker push $DOCKER_IMAGE_TAG
+    fi
+else
+    echo "Invalid parameter: $1"
+    echo "Please supply a valid package version for the Docker image"
+    exit 1
 fi
